core/urls.py
from django.urls import path 
from core import views, transfer, transaction, payment_request, credit_card

app_name = "core"

urlpatterns = [
    path("", views.sample, name="index"),

    #transfers
    path("search-account/", transfer.search_user_by_account_number, name="search-account"),
    path("amount-transfer/<account_number>/", transfer.amount_transfer, name="amount-transfer"),
    path("amount-transfer-process/<account_number>/", transfer.AmountTransferProcess, name="amount-transfer-process"),
    path("transfer-confirmation/<account_number>/<transaction_id>/", transfer.TransferConfirmation, name="transfer-confirmation"),
    path("transfer-process/<account_number>/<transaction_id>/", transfer.transfer_process, name="transfer-process"),
    path("transfer-completed/<account_number>/<transaction_id>/", transfer.transfer_completed, name="transfer-completed"),

    #transactions(list)
    path("transaction-list/", transaction.transaction_list, name="transaction-list"),   
    path("transaction-details/<transaction_id>", transaction.transaction_details, name="transaction-details"),   

    #payment-request
    path("search-requested-account/", payment_request.search_user_request, name="search-requested-account"),
    path("request_amount_transfer/<account_number>/", payment_request.request_amount_transfer, name="request_amount_transfer"),
    path("request_amount_transfer_process/<account_number>/", payment_request.request_amount_transfer_process, name="request_amount_transfer_process"),
    path("request_confirmation/<request_reciever_account_number>/<transaction_id>", payment_request.request_confirmation, name="request_confirmation"),
    path("amount_request_final_process/<request_reciever_account_number>/<transaction_id>", payment_request.amount_request_final_process, name="amount_request_final_process"),
    path("request-completed/<request_reciever_account_number>/<transaction_id>", payment_request.request_completed, name="request-completed"),

    # request settlement confirmation
    path("settlement_confirmation/<request_sender_account_number>/<transaction_id>", payment_request.settlement_confirmation, name="settlement_confirmation"),
    path("settlement_process/<request_sender_account_number>/<transaction_id>", payment_request.settlement_process, name="settlement_process"),
    path("settlement_completed/<request_sender_account_number>/<transaction_id>", payment_request.settlement_completed, name="settlement_completed"),
    path("delete_request/<account_number>/<transaction_id>", payment_request.delete_request, name="delete_request"),

    # credit card
    path("card_detail/<card_id>", credit_card.credit_card_detail, name="card_detail"),
    path("fund_credit_card/<card_id>", credit_card.fund_credit_card, name="fund_credit_card"),
    path("withdraw_fund/<card_id>", credit_card.withdraw_fund, name="withdraw_fund"),
    path("delete_card/<card_id>", credit_card.delete_card, name="delete_card"),


]

payment_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path("user/", include("userauths.urls", "userauths")),
    path("", include("core.urls", "core")),
    path("account/", include("account.urls", "account")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/payment-request/request-amount-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}

{% block content %}

   

   

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Request</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Request</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account.user.kyc.image.url }}" alt="image" style="width:100px; height:100px; border-radius:50%; object-fit:cover">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name }}</p>
                                        <span class="mdr">{{account.account_number}}</span>
                                        <span class="mdr">{{account.user.email}}</span>
                                    </div>
                                </div>
                                
                                <div class="right">
                                    <a href="{% url 'core:search-account'%}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Request Details</h6>
                            <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>You request</span>
                                        <b>{{transaction.amount}}</b>
                                    </li>
                        
                                    <li>
                                        <span>To: </span>
                                        <b><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="d3bebca1a1baa0e1e193b4beb2babffdb0bcbe"><b>{{account.kyc.full_name}}<b></a></b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Purpose</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer will be receive on </span>
                                        <b>{{transaction.date}}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="pay-step-2.html">Previous Step</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Request</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Your Request</h4>
                                            <p>We have sent a verification code on your phone + Number +44831***932. Please enter verification code below</p>
                                            <form action="{% url "core:amount_request_final_process" account.account_number transaction.transaction_id %}"method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input type="text" minlength="4" maxlength="4" name="pin-number">
                                                </div>
                                                <a href="javascript:void(0)">Don’t receive a code?</a>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="{% static 'assets/images/icon/success.png' %}" alt="icon">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->

{% endblock content %}

templates/payment-request/request-amount-transfer.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}

{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 2 of 3</span>
                            <h5>Set Amount of transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account.user.kyc.image.url }}" alt="image" style="width:100px; height:100px; border-radius:50%; object-fit:cover">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name }}</p>
                                        <span class="mdr">{{account.account_number}}</span>
                                        <span class="mdr">{{account.user.email}}</span>
                                    </div>
                                </div>
                                
                                <div class="right">
                                    <a href="{% url 'core:search-account'%}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                           
                    <form action="{% url 'core:request_amount_transfer_process' account.account_number %}" method="POST">
                        {% csrf_token %}
                        <div class="send-banance">
                            <span class="mdr">You Request</span>
                            <div class="input-area"> 
                                <input class="xxlr" placeholder="Enter Amount" type="number" name="request_amount" id="amount_sent">
                                <select>
                                    <option value="1">USD</option>
                                    <option value="2">USD</option>
                                    <option value="3">USD</option>
                                </select>
                            </div>
                            
                            
                            
                        </div>
                      
                        <div class="send-banance">
                            <span class="mdr">Request Description</span>
                            <div class="input-area">
                                <input class="xxlr"  placeholder="Description" type="text" name="request_description" id="amount_sent">
                            </div>
                        <br>
                        
                        <div class="footer-area mt-40">
                            <a href="{% url "core:search-requested-account" %}">Previous Step</a>
                            <button type="submit" class="active" style="padding: 10px; border-radius:10px; background:rgb(90, 0, 225); color:#fff">Next</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

{% endblock content %}

templates/payment-request/request-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}


{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Requested</h3>
                            <p>Payment Request was sent to <b>{{account.user.kyc.full_name}}<b></p>
                            <h5>Manage payment request | Request another Payment</h5>
                        </div>
                        <div class="share-link">
                            <p>Share direct link with your  payer</p>
                            <ul class="d-flex align-items-center justify-content-center">
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/whatsapp.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/skype.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/messenger.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/copy-link.png' %}" alt="icon"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
 
{% endblock content %}

templates/payment-request/settlement-completed.html
{% extends "partials/dashboard-base.html" %}
{% load static %}


{% block content %}

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3 receive-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Request a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets1/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="request-submitted pb-120 text-center">
                        <div class="top-area">
                            <div class="icon-area">
                                <img src="{% static 'assets1/images/icon/submitted-icon.png' %}" alt="icon">
                            </div>
                            <h3>Sent</h3>
                            <p> Requested payment  was sent to <b>{{account.user.kyc.full_name}}<b></p>
                            <h5>Manage payment request | Request another Payment</h5>
                        </div>
                        <div class="share-link">
                            <p>Share direct link with your  payer</p>
                            <ul class="d-flex align-items-center justify-content-center">
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/whatsapp.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/skype.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/messenger.png' %}" alt="icon"></a>
                                </li>
                                <li>
                                    <a href="javascript:void(0)"><img src="{% static 'assets/images/icon/copy-link.png' %}" alt="icon"></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->
 
{% endblock content %}

templates/payment-request/settlement-confirmation.html
{% extends "partials/dashboard-base.html" %}
{% load static %}
{% load humanize %}

{% block content %}

   

   

    <!-- Dashboard Section start -->
    <section class="dashboard-section body-collapse pay step step-2 step-3">
        <div class="overlay pt-120">
            <div class="container-fruid">
                <div class="main-content">
                    <div class="head-area d-flex align-items-center justify-content-between">
                        <h4>Make a Payment</h4>
                        <div class="icon-area">
                            <img src="{% static 'assets/images/icon/support-icon.png' %}" alt="icon">
                        </div>
                    </div>
                    <div class="choose-recipient">
                        <div class="step-area">
                            <span class="mdr">Step 3 of 3</span>
                            <h5>Confirm Your Transfer</h5>
                        </div>
                        <div class="user-select">
                            <div class="single-user">
                                <div class="left d-flex align-items-center">
                                    <div class="img-area">
                                        <img src="{{ account.user.kyc.image.url }}" alt="image" style="width:100px; height:100px; border-radius:50%; object-fit:cover">
                                    </div>
                                    <div class="text-area">
                                        <p>{{ account.user.kyc.full_name }}</p>
                                        <span class="mdr">{{account.account_number}}</span>
                                        <span class="mdr">{{account.user.email}}</span>
                                    </div>
                                </div>
                                
                                <div class="right">
                                    <a href="{% url 'core:search-account'%}">
                                        <i class="icon-h-edit"></i>
                                        Edit
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="payment-details">
                        <div class="top-area">
                            <h6>Payment Details</h6>
                            <div class="right">
                                <a href="javascript:void(0)">
                                    <i class="icon-h-edit"></i>
                                    Edit
                                </a>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xl-6">
                                <ul class="details-list">
                                    <li>
                                        <span>Amount Requested                                        </span>
                                        <b>{{transaction.amount}}</b>
                                    </li>
                                    <li>
                                        <span>Recipient gets</span>
                                        <b>{{transaction.amount}}</b>
                                    </li>
                                    <li>
                                        <span>E-mail of receiver</span>
                                        <b><a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="d3bebca1a1baa0e1e193b4beb2babffdb0bcbe"><b>{{account.user.email}}<b></a></b>
                                    </li>
                                    <li>
                                        <span>Fee</span>
                                        <b>Free</b>
                                    </li>
                                    <li>
                                        <span>Purpose</span>
                                        <b>{{transaction.description}}</b>
                                    </li>
                                    <li>
                                        <span>Transfer will be receive on </span>
                                        <b>{{transaction.date}}</b>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <form action="#">
                        <div class="checkbox">
                            <input type="checkbox" id="confirm">
                            <label for="confirm">I confirm the payment details above</label>
                        </div>
                        <div class="footer-area mt-40">
                            <a href="{% url "core:transaction-list" %}">Previous Step</a>
                            <a href="javascript:void(0)" class="transferMod active" data-bs-toggle="modal" data-bs-target="#transferMod">Settle Now</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Dashboard Section end -->

    <!-- Transfer Popup start -->
    <div class="transfer-popup">
        <div class="container-fruid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="modal fade" id="transferMod" aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered">
                            <ul class="nav nav-tabs d-none" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="transfer-tab" data-bs-toggle="tab" data-bs-target="#transfer" type="button" role="tab" aria-controls="transfer" aria-selected="true">transfer</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="success-tab" data-bs-toggle="tab" data-bs-target="#success" type="button" role="tab" aria-controls="success" aria-selected="false">Confirm</button>
                                </li>
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="transfer" role="tabpanel" aria-labelledby="transfer-tab">
                                    <div class="modal-content">
                                        <div class="modal-header mb-60 justify-content-between">
                                            <a href="javascript:void(0)">
                                                <i class="icon-a-left-arrow"></i>
                                                Back
                                            </a>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content">
                                            <h4>Confirm Transfer!</h4>
                                            <p>We have sent a verification code on your phone + Number +44831***932. Please enter verification code below</p>
                                            <form action="{% url "core:settlement_process" account.account_number transaction.transaction_id %}"method="POST">
                                                {% csrf_token %}
                                                <div class="userInput">
                                                    <input type="text" minlength="4" maxlength="4" name="pin-number">
                                                </div>
                                                <a href="javascript:void(0)">Don’t receive a code?</a>
                                                <button type="submit" class="mt-60 confirm">Confirm</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="success" role="tabpanel" aria-labelledby="success-tab">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="btn-close d-md-none d-block" data-bs-dismiss="modal" aria-label="Close"><i class="fa-solid fa-xmark"></i></button>
                                        </div>
                                        <div class="main-content text-center pt-120 pb-120">
                                            <img src="{% static 'assets/images/icon/success.png' %}" alt="icon">
                                            <h3>Success</h3>
                                            <p>Transfer was completed.</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Transfer Popup start -->

{% endblock content %}

   